// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action XFileAction;
    
    private Gtk.Action GimmeHelpAction;
    
    private Gtk.Action AboutAction;
    
    private Gtk.Action QuitAction;
    
    private Gtk.Action SomeEditMenuAction;
    
    private Gtk.Action NewAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Table table1;
    
    private Gtk.Button btnTest1;
    
    private Gtk.Button button1;
    
    private Gtk.ComboBoxEntry cbeTest;
    
    private Gtk.ComboBox cbxTest;
    
    private Gtk.CheckButton chkTest;
    
    private Gtk.Label lblTest1;
    
    private Gtk.RadioButton radiobutton1;
    
    private Gtk.RadioButton radiobutton2;
    
    private Gtk.RadioButton radTest1;
    
    private Gtk.RadioButton radTest2;
    
    private Gtk.Entry txtEntry;
    
    private Gtk.VScrollbar vscrollbar1;
    
    private Gtk.HScrollbar hscrollbar1;
    
    private Gtk.ProgressBar progressbar1;
    
    private Gtk.Statusbar statusbar1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.XFileAction = new Gtk.Action("XFileAction", Mono.Unix.Catalog.GetString("XFile"), null, null);
        this.XFileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.XFileAction, null);
        this.GimmeHelpAction = new Gtk.Action("GimmeHelpAction", Mono.Unix.Catalog.GetString("GimmeHelp"), null, null);
        this.GimmeHelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.GimmeHelpAction, null);
        this.AboutAction = new Gtk.Action("AboutAction", Mono.Unix.Catalog.GetString("About"), null, null);
        this.AboutAction.ShortLabel = Mono.Unix.Catalog.GetString("About");
        w1.Add(this.AboutAction, null);
        this.QuitAction = new Gtk.Action("QuitAction", Mono.Unix.Catalog.GetString("Quit"), null, null);
        this.QuitAction.ShortLabel = Mono.Unix.Catalog.GetString("Quit");
        w1.Add(this.QuitAction, null);
        this.SomeEditMenuAction = new Gtk.Action("SomeEditMenuAction", Mono.Unix.Catalog.GetString("SomeEditMenu"), null, null);
        this.SomeEditMenuAction.ShortLabel = Mono.Unix.Catalog.GetString("SomeEditMenu");
        w1.Add(this.SomeEditMenuAction, null);
        this.NewAction = new Gtk.Action("NewAction", Mono.Unix.Catalog.GetString("New"), null, null);
        this.NewAction.ShortLabel = Mono.Unix.Catalog.GetString("New");
        w1.Add(this.NewAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='XFileAction' action='XFileAction'><menuitem name='NewAction' action='NewAction'/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='SomeEditMenuAction' action='SomeEditMenuAction'/><menu name='GimmeHelpAction' action='GimmeHelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.table1 = new Gtk.Table(((uint)(4)), ((uint)(3)), false);
        this.table1.Name = "table1";
        this.table1.RowSpacing = ((uint)(6));
        this.table1.ColumnSpacing = ((uint)(6));
        // Container child table1.Gtk.Table+TableChild
        this.btnTest1 = new Gtk.Button();
        this.btnTest1.CanFocus = true;
        this.btnTest1.Name = "btnTest1";
        this.btnTest1.UseUnderline = true;
        this.btnTest1.Label = Mono.Unix.Catalog.GetString("hey ya");
        this.table1.Add(this.btnTest1);
        Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.btnTest1]));
        w3.LeftAttach = ((uint)(2));
        w3.RightAttach = ((uint)(3));
        w3.XOptions = ((Gtk.AttachOptions)(4));
        w3.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        // Container child button1.Gtk.Container+ContainerChild
        Gtk.Alignment w4 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w5 = new Gtk.HBox();
        w5.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w6 = new Gtk.Image();
        w6.Pixbuf = new Gdk.Pixbuf(System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "../../../../../../test/samples/opensuse60x38.gif"));
        w5.Add(w6);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w8 = new Gtk.Label();
        w8.LabelProp = Mono.Unix.Catalog.GetString("button1");
        w8.UseUnderline = true;
        w5.Add(w8);
        w4.Add(w5);
        this.button1.Add(w4);
        this.table1.Add(this.button1);
        Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.button1]));
        w12.TopAttach = ((uint)(3));
        w12.BottomAttach = ((uint)(4));
        w12.XOptions = ((Gtk.AttachOptions)(4));
        w12.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.cbeTest = Gtk.ComboBoxEntry.NewText();
        this.cbeTest.AppendText(Mono.Unix.Catalog.GetString("First element"));
        this.cbeTest.AppendText(Mono.Unix.Catalog.GetString("Second element"));
        this.cbeTest.AppendText(Mono.Unix.Catalog.GetString("Third element"));
        this.cbeTest.Name = "cbeTest";
        this.table1.Add(this.cbeTest);
        Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.cbeTest]));
        w13.TopAttach = ((uint)(1));
        w13.BottomAttach = ((uint)(2));
        w13.LeftAttach = ((uint)(2));
        w13.RightAttach = ((uint)(3));
        w13.XOptions = ((Gtk.AttachOptions)(4));
        w13.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.cbxTest = Gtk.ComboBox.NewText();
        this.cbxTest.AppendText(Mono.Unix.Catalog.GetString("FirstItem"));
        this.cbxTest.AppendText(Mono.Unix.Catalog.GetString("SecondItem"));
        this.cbxTest.AppendText(Mono.Unix.Catalog.GetString("LastItem"));
        this.cbxTest.Name = "cbxTest";
        this.table1.Add(this.cbxTest);
        Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.cbxTest]));
        w14.TopAttach = ((uint)(1));
        w14.BottomAttach = ((uint)(2));
        w14.LeftAttach = ((uint)(1));
        w14.RightAttach = ((uint)(2));
        w14.XOptions = ((Gtk.AttachOptions)(4));
        w14.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.chkTest = new Gtk.CheckButton();
        this.chkTest.CanFocus = true;
        this.chkTest.Name = "chkTest";
        this.chkTest.Label = Mono.Unix.Catalog.GetString("checkbutton1");
        this.chkTest.DrawIndicator = true;
        this.chkTest.UseUnderline = true;
        this.table1.Add(this.chkTest);
        Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.chkTest]));
        w15.TopAttach = ((uint)(1));
        w15.BottomAttach = ((uint)(2));
        w15.XOptions = ((Gtk.AttachOptions)(4));
        w15.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.lblTest1 = new Gtk.Label();
        this.lblTest1.Name = "lblTest1";
        this.lblTest1.LabelProp = Mono.Unix.Catalog.GetString("This is a test message\nin a label");
        this.table1.Add(this.lblTest1);
        Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table1[this.lblTest1]));
        w16.XOptions = ((Gtk.AttachOptions)(4));
        w16.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.radiobutton1 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("radiobutton1"));
        this.radiobutton1.CanFocus = true;
        this.radiobutton1.Name = "radiobutton1";
        this.radiobutton1.DrawIndicator = true;
        this.radiobutton1.UseUnderline = true;
        this.radiobutton1.Group = new GLib.SList(System.IntPtr.Zero);
        this.table1.Add(this.radiobutton1);
        Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table1[this.radiobutton1]));
        w17.TopAttach = ((uint)(3));
        w17.BottomAttach = ((uint)(4));
        w17.LeftAttach = ((uint)(1));
        w17.RightAttach = ((uint)(2));
        w17.XOptions = ((Gtk.AttachOptions)(4));
        w17.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.radiobutton2 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("radiobutton2"));
        this.radiobutton2.CanFocus = true;
        this.radiobutton2.Name = "radiobutton2";
        this.radiobutton2.DrawIndicator = true;
        this.radiobutton2.UseUnderline = true;
        this.radiobutton2.Group = this.radiobutton1.Group;
        this.table1.Add(this.radiobutton2);
        Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table1[this.radiobutton2]));
        w18.TopAttach = ((uint)(3));
        w18.BottomAttach = ((uint)(4));
        w18.LeftAttach = ((uint)(2));
        w18.RightAttach = ((uint)(3));
        w18.XOptions = ((Gtk.AttachOptions)(4));
        w18.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.radTest1 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("rad Opt 0"));
        this.radTest1.CanFocus = true;
        this.radTest1.Name = "radTest1";
        this.radTest1.DrawIndicator = true;
        this.radTest1.UseUnderline = true;
        this.radTest1.Group = new GLib.SList(System.IntPtr.Zero);
        this.table1.Add(this.radTest1);
        Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table1[this.radTest1]));
        w19.TopAttach = ((uint)(2));
        w19.BottomAttach = ((uint)(3));
        w19.LeftAttach = ((uint)(1));
        w19.RightAttach = ((uint)(2));
        w19.XOptions = ((Gtk.AttachOptions)(4));
        w19.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.radTest2 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("rad Opt 1"));
        this.radTest2.CanFocus = true;
        this.radTest2.Name = "radTest2";
        this.radTest2.DrawIndicator = true;
        this.radTest2.UseUnderline = true;
        this.radTest2.Group = this.radTest1.Group;
        this.table1.Add(this.radTest2);
        Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table1[this.radTest2]));
        w20.TopAttach = ((uint)(2));
        w20.BottomAttach = ((uint)(3));
        w20.LeftAttach = ((uint)(2));
        w20.RightAttach = ((uint)(3));
        w20.XOptions = ((Gtk.AttachOptions)(4));
        w20.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.txtEntry = new Gtk.Entry();
        this.txtEntry.CanFocus = true;
        this.txtEntry.Name = "txtEntry";
        this.txtEntry.Text = Mono.Unix.Catalog.GetString("test text");
        this.txtEntry.IsEditable = true;
        this.txtEntry.InvisibleChar = '●';
        this.table1.Add(this.txtEntry);
        Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table1[this.txtEntry]));
        w21.LeftAttach = ((uint)(1));
        w21.RightAttach = ((uint)(2));
        w21.XOptions = ((Gtk.AttachOptions)(4));
        w21.YOptions = ((Gtk.AttachOptions)(4));
        this.hbox1.Add(this.table1);
        Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox1[this.table1]));
        w22.Position = 1;
        w22.Expand = false;
        w22.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.vscrollbar1 = new Gtk.VScrollbar(null);
        this.vscrollbar1.Name = "vscrollbar1";
        this.vscrollbar1.Adjustment.Upper = 100;
        this.vscrollbar1.Adjustment.PageIncrement = 10;
        this.vscrollbar1.Adjustment.PageSize = 10;
        this.vscrollbar1.Adjustment.StepIncrement = 1;
        this.hbox1.Add(this.vscrollbar1);
        Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.hbox1[this.vscrollbar1]));
        w23.Position = 2;
        w23.Expand = false;
        w23.Fill = false;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w24.Position = 1;
        w24.Expand = false;
        w24.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hscrollbar1 = new Gtk.HScrollbar(null);
        this.hscrollbar1.Name = "hscrollbar1";
        this.hscrollbar1.Adjustment.Upper = 100;
        this.hscrollbar1.Adjustment.PageIncrement = 10;
        this.hscrollbar1.Adjustment.PageSize = 10;
        this.hscrollbar1.Adjustment.StepIncrement = 1;
        this.vbox1.Add(this.hscrollbar1);
        Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox1[this.hscrollbar1]));
        w25.Position = 2;
        w25.Expand = false;
        w25.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.progressbar1 = new Gtk.ProgressBar();
        this.progressbar1.Name = "progressbar1";
        this.vbox1.Add(this.progressbar1);
        Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.vbox1[this.progressbar1]));
        w26.Position = 3;
        w26.Expand = false;
        w26.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar1 = new Gtk.Statusbar();
        this.statusbar1.Name = "statusbar1";
        this.statusbar1.Spacing = 6;
        this.vbox1.Add(this.statusbar1);
        Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
        w27.Position = 4;
        w27.Expand = false;
        w27.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 678;
        this.DefaultHeight = 288;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
