// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Table table1;
    
    private Gtk.Button btnTest1;
    
    private Gtk.ComboBoxEntry cbeTest;
    
    private Gtk.ComboBox cbxTest;
    
    private Gtk.CheckButton chkTest;
    
    private Gtk.Label lblTest1;
    
    private Gtk.RadioButton radTest1;
    
    private Gtk.RadioButton radTest2;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.table1 = new Gtk.Table(((uint)(3)), ((uint)(3)), false);
        this.table1.Name = "table1";
        this.table1.RowSpacing = ((uint)(6));
        this.table1.ColumnSpacing = ((uint)(6));
        // Container child table1.Gtk.Table+TableChild
        this.btnTest1 = new Gtk.Button();
        this.btnTest1.CanFocus = true;
        this.btnTest1.Name = "btnTest1";
        this.btnTest1.UseUnderline = true;
        this.btnTest1.Label = Mono.Unix.Catalog.GetString("hey ya");
        this.table1.Add(this.btnTest1);
        Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.btnTest1]));
        w1.LeftAttach = ((uint)(2));
        w1.RightAttach = ((uint)(3));
        w1.XOptions = ((Gtk.AttachOptions)(4));
        w1.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.cbeTest = Gtk.ComboBoxEntry.NewText();
        this.cbeTest.Name = "cbeTest";
        this.table1.Add(this.cbeTest);
        Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.cbeTest]));
        w2.TopAttach = ((uint)(1));
        w2.BottomAttach = ((uint)(2));
        w2.LeftAttach = ((uint)(2));
        w2.RightAttach = ((uint)(3));
        w2.XOptions = ((Gtk.AttachOptions)(4));
        w2.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.cbxTest = Gtk.ComboBox.NewText();
        this.cbxTest.AppendText(Mono.Unix.Catalog.GetString("FirstItem"));
        this.cbxTest.AppendText(Mono.Unix.Catalog.GetString("SecondItem"));
        this.cbxTest.AppendText(Mono.Unix.Catalog.GetString("LastItem"));
        this.cbxTest.Name = "cbxTest";
        this.table1.Add(this.cbxTest);
        Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.cbxTest]));
        w3.TopAttach = ((uint)(1));
        w3.BottomAttach = ((uint)(2));
        w3.LeftAttach = ((uint)(1));
        w3.RightAttach = ((uint)(2));
        w3.XOptions = ((Gtk.AttachOptions)(4));
        w3.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.chkTest = new Gtk.CheckButton();
        this.chkTest.CanFocus = true;
        this.chkTest.Name = "chkTest";
        this.chkTest.Label = Mono.Unix.Catalog.GetString("checkbutton1");
        this.chkTest.DrawIndicator = true;
        this.chkTest.UseUnderline = true;
        this.table1.Add(this.chkTest);
        Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.chkTest]));
        w4.TopAttach = ((uint)(1));
        w4.BottomAttach = ((uint)(2));
        w4.XOptions = ((Gtk.AttachOptions)(4));
        w4.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.lblTest1 = new Gtk.Label();
        this.lblTest1.Name = "lblTest1";
        this.lblTest1.LabelProp = Mono.Unix.Catalog.GetString("This is a test message\nin a label");
        this.table1.Add(this.lblTest1);
        Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.lblTest1]));
        w5.XOptions = ((Gtk.AttachOptions)(4));
        w5.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.radTest1 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("rad Opt 0"));
        this.radTest1.CanFocus = true;
        this.radTest1.Name = "radTest1";
        this.radTest1.DrawIndicator = true;
        this.radTest1.UseUnderline = true;
        this.radTest1.Group = new GLib.SList(System.IntPtr.Zero);
        this.table1.Add(this.radTest1);
        Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.radTest1]));
        w6.TopAttach = ((uint)(2));
        w6.BottomAttach = ((uint)(3));
        w6.LeftAttach = ((uint)(1));
        w6.RightAttach = ((uint)(2));
        w6.XOptions = ((Gtk.AttachOptions)(4));
        w6.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.radTest2 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("rad Opt 1"));
        this.radTest2.CanFocus = true;
        this.radTest2.Name = "radTest2";
        this.radTest2.DrawIndicator = true;
        this.radTest2.UseUnderline = true;
        this.radTest2.Group = this.radTest1.Group;
        this.table1.Add(this.radTest2);
        Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.radTest2]));
        w7.TopAttach = ((uint)(2));
        w7.BottomAttach = ((uint)(3));
        w7.LeftAttach = ((uint)(2));
        w7.RightAttach = ((uint)(3));
        w7.XOptions = ((Gtk.AttachOptions)(4));
        w7.YOptions = ((Gtk.AttachOptions)(4));
        this.hbox1.Add(this.table1);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox1[this.table1]));
        w8.Position = 1;
        w8.Expand = false;
        w8.Fill = false;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w9.Position = 1;
        w9.Expand = false;
        w9.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 487;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
