# the tests_list list keeps track of enabled tests.  A test will be
# executed only after the tests sample application is added to this list

# this allows tests to be worked on and developed in SVN, but only executed
# as part of the test suite when they are ready

# only add finished tests that should execute successfully to this list

tests_list = [
    "button_basic_ops.py",
    "checkbox_basic_ops.py",
    "checkedlistbox_basic_ops.py",
    "colordialog_basic_ops.py",
    "columnheader_basic_ops.py",
    "combobox_dropdown_ops.py",
    "combobox_dropdownlist_ops.py",
    "combobox_simple_ops.py",
    "combobox_stylechanges_basic_ops.py",
    "containercontrol_basic_ops.py",
    "contextmenu_basic_ops.py",
    "contextmenustrip_basic_ops.py",
    "datagrid_basic_ops.py",
    "datagridboolcolumn_basic_ops.py",
    "datagridtextboxcolumn_basic_ops.py",
    "datagridcomboboxcolumn_basic_ops.py",
    "datagridview_detail_ops.py",
    "datetimepicker_dropdown_ops.py",
    "datetimepicker_showupdown_ops.py",
    "domainupdown_basic_ops.py",
    "errorprovider_basic_ops.py",
    "flowlayoutpanel_basic_ops.py",
    "fontdialog_basic_ops.py",
    "form_basic_ops.py",
    "groupbox_basic_ops.py",
    "helpprovider_basic_ops.py",
    "hscrollbar_basic_ops.py",
    "label_basic_ops.py",
    "linklabel_basic_ops.py",
    "listbox_basic_ops.py", 
    "listview_detail_ops.py",
    "listview_largeimage_ops.py",
    "listview_smallimage_ops.py",
    "listview_list_ops.py",
    "maskedtextbox_basic_ops.py",
    "mainmenu_basic_ops.py",
    "menustrip_basic_ops.py",
    "monthcalendar_basic_ops.py",
    "notifyicon_basic_ops.py",
    "numericupdown_basic_ops.py",
    "openfiledialog_basic_ops.py",
    "pagesetupdialog_basic_ops.py",
    "panel_basic_ops.py",
    "picturebox_basic_ops.py",
    "printpreviewcontrol_basic_ops.py",
    "printpreviewdialog_basic_ops.py",
    "progressbar_basic_ops.py",
    "propertygrid_basic_ops.py",
    "radiobutton_basic_ops.py",
    "richtextbox_basic_ops.py",
    "savefiledialog_basic_ops.py",
    "scrollbar_basic_ops.py",
    "splitter_horizontal.py",
    "splitter_vertical.py",
    "statusbarpanel_basic_ops.py",
    "statusstrip_basic_ops.py",
    "tabcontrol_basic_ops.py",
    "tabpage_basic_ops.py",
    "tablelayoutpanel_basic_ops.py",
    "textbox_basic_ops.py",
    "threadexceptiondialog_basic_ops.py",
    "toolbar_basic_ops.py",
    "toolbarbutton_basic_ops.py",
    "toolstrip_basic_ops.py",
    "toolstripbutton_basic_ops.py",
    "toolstripcombobox_basic_ops.py",
    "toolstripdropdownbutton_basic_ops.py",
    "toolstriplabel_basic_ops.py",
    "toolstripmenuitem_basic_ops.py",
    "toolstripprogressbar_basic_ops.py",
    "toolstripseparator_basic_ops.py",
    "toolstripsplitbutton_basic_ops.py",
    "toolstriptextbox_basic_ops.py",
    "tooltip_basic_ops.py",
    "trackbar_basic_ops.py",
    "treeview_basic_ops.py",
    "vscrollbar_basic_ops.py",
]
