# the tests_list list keeps track of enabled tests.  A test will be
# executed only after the tests sample application is added to this list

# this allows tests to be worked on and developed in SVN, but only executed
# as part of the test suite when they are ready

# only add finished tests that should execute successfully to this list

tests_list = [
	"winforms/button-regression.py",
	"winforms/checkbox-regression.py",
	"winforms/checkedlistbox-regression.py",
	"winforms/colordialog-regression.py",
	"winforms/columnheader-regression.py",
	"winforms/combobox_dropdownlist-regression.py",
	"winforms/combobox_dropdown-regression.py",
	"winforms/combobox_simple-regression.py",
	"winforms/combobox_stylechanges-regression.py",
	"winforms/containercontrol-regression.py",
	"winforms/contextmenu-regression.py",
	"winforms/contextmenustrip-regression.py",
	"winforms/datagridboolcolumn-regression.py",
	"winforms/datagridcomboboxcolumn-regression.py",
	"winforms/datagrid-regression.py",
	"winforms/datagridtextboxcolumn-regression.py",
	"winforms/datagridview_detail-regression.py",
	"winforms/datetimepicker_dropdown-regression.py",
	"winforms/datetimepicker_showupdown-regression.py",
	"winforms/domainupdown-regression.py",
	"winforms/errorprovider-regression.py",
	"winforms/flowlayoutpanel-regression.py",
	"winforms/fontdialog-regression.py",
	"winforms/form-regression.py",
	"winforms/groupbox-regression.py",
	"winforms/helpers.py",
	"winforms/helpprovider-regression.py",
	"winforms/hscrollbar-regression.py",
	"winforms/label-regresion.py",
	"winforms/linklabel-regression.py",
	"winforms/listbox-regression.py",
	"winforms/listview_largeimage-regression.py",
	"winforms/listview_list-regression.py",
	"winforms/listview-regression.py",
	"winforms/listview_smallimage-regression.py",
	"winforms/mainmenu-regression.py",
	"winforms/maskedtextbox-regression.py",
	"winforms/menustrip-regression.py",
	"winforms/monthcalendar-regression.py",
	"winforms/notifyicon-regression.py",
	"winforms/numericupdown-regression.py",
	"winforms/openfiledialog-regression.py",
	"winforms/pagesetupdialog-regression.py",
	"winforms/panel-regression.py",
	"winforms/picturebox-regression.py",
	"winforms/printpreviewcontrol-regression.py",
	"winforms/printpreviewdialog-regression.py",
	"winforms/progressbar-regression.py",
	"winforms/propertygrid-regression.py",
	"winforms/radiobutton-regression.py",
	"winforms/richtextbox-regression.py",
	"winforms/savefiledialog-regression.py",
	"winforms/scrollbar-regression.py",
	"winforms/splitter_horizontal-regression.py",
	"winforms/splitter_vertical-regression.py",
	"winforms/states.py",
	"winforms/statusbarpanel-regression.py",
	"winforms/statusbar-regression.py",
	"winforms/statusstrip-regression.py",
	"winforms/tabcontrol-regression.py",
	"winforms/tablelayoutpanel-regression.py",
	"winforms/tabpage-regression.py",
	"winforms/textbox-regression.py",
	"winforms/threadexceptiondialog-regression.py",
	"winforms/toolbarbutton-regression.py",
	"winforms/toolbar-regression.py",
	"winforms/toolstripbutton-regression.py",
	"winforms/toolstripcombobox-regression.py",
	"winforms/toolstripdropdownbutton-regression.py",
	"winforms/toolstriplabel-regression.py",
	"winforms/toolstripmenuitem-regression.py",
	"winforms/toolstripprogressbar-regression.py",
	"winforms/toolstrip-regression.py",
	"winforms/toolstripseparator-regression.py",
	"winforms/toolstripsplitbutton-regression.py",
	"winforms/toolstriptextbox-regression.py",
	"winforms/tooltip-regression.py",
	"winforms/trackbar-regression.py",
	"winforms/treeview-regression.py",
	"winforms/vscrollbar-regression.py"
]
