# the tests_list list keeps track of enabled tests.  a test will be
# executed only after the tests sample application is added to this list

# this allows tests to be worked on and developed in svn, but only executed
# as part of the test suite when they are ready

# only add finished tests that should execute successfully to this list

winforms_tests_list = [
	"button-regression.py",
	"checkbox-regression.py",
	"checkedlistbox-regression.py",
	"colordialog-regression.py",
	"columnheader-regression.py",
	"combobox_dropdownlist-regression.py",
	"combobox_dropdown-regression.py",
	"combobox_simple-regression.py",
	"combobox_stylechanges-regression.py",
	"containercontrol-regression.py",
	"contextmenu-regression.py",
	"contextmenustrip-regression.py",
	"datagridboolcolumn-regression.py",
	"datagridcomboboxcolumn-regression.py",
	"datagrid-regression.py",
	"datagridtextboxcolumn-regression.py",
	"datagridview_detail-regression.py",
	"datetimepicker_dropdown-regression.py",
	"datetimepicker_showupdown-regression.py",
	"domainupdown-regression.py",
	"errorprovider-regression.py",
	"flowlayoutpanel-regression.py",
	"fontdialog-regression.py",
	"form-regression.py",
	"groupbox-regression.py",
	"helpprovider-regression.py",
	"hscrollbar-regression.py",
	#"label-regression.py",
	"linklabel-regression.py",
	"listbox-regression.py",
	"listview_largeimage-regression.py",
	"listview_list-regression.py",
	"listview-regression.py",
	"listview_smallimage-regression.py",
	"mainmenu-regression.py",
	"maskedtextbox-regression.py",
	"menustrip-regression.py",
	"monthcalendar-regression.py",
	"notifyicon-regression.py",
	"numericupdown-regression.py",
	"openfiledialog-regression.py",
	"pagesetupdialog-regression.py",
	"panel-regression.py",
	"picturebox-regression.py",
	"printpreviewcontrol-regression.py",
	"printpreviewdialog-regression.py",
	"progressbar-regression.py",
	"propertygrid-regression.py",
	"radiobutton-regression.py",
	"richtextbox-regression.py",
	"savefiledialog-regression.py",
	"scrollbar-regression.py",
	"splitter_horizontal-regression.py",
	"splitter_vertical-regression.py",
	"statusbarpanel-regression.py",
	"statusbar-regression.py",
	"statusstrip-regression.py",
	"tabcontrol-regression.py",
	"tablelayoutpanel-regression.py",
	"tabpage-regression.py",
	"textbox-regression.py",
	"threadexceptiondialog-regression.py",
	"toolbarbutton-regression.py",
	"toolbar-regression.py",
	"toolstripbutton-regression.py",
	"toolstripcombobox-regression.py",
	"toolstripdropdownbutton-regression.py",
	"toolstriplabel-regression.py",
	"toolstripmenuitem-regression.py",
	"toolstripprogressbar-regression.py",
	"toolstrip-regression.py",
	"toolstripseparator-regression.py",
	"toolstripsplitbutton-regression.py",
	"toolstriptextbox-regression.py",
	"tooltip-regression.py",
	"trackbar-regression.py",
	"treeview-regression.py",
	"vscrollbar-regression.py"
]

moonlight_tests_list = [
	"button-regression.py",
	"checkbox-regression.py",
	"combobox-regression.py",
	"gridsplitter-regression.py",
	"hyperlinkbutton-regression.py",
	"image-regression.py",
	"listbox-regression.py",
	"passwordbox-regression.py",
	"progressbar-regression.py",
	"radiobutton-regression.py",
	"repeatbutton-regression.py",
	"scrollbar-regression.py",
	"scrollviewer-regression.py",
	"slider-regression.py",
	"textblock-regression.py",
	"textbox-regression.py",
	"thumb-regression.py",
	"togglebutton-regression.py"
]

uiaclientwinforms_tests_list = [
	"winforms_keepasstests_runtestcase101-regression.py",
	"winforms_keepasstests_runtestcase102-regression.py",
	"winforms_keepasstests_runtestcase103-regression.py",
	"winforms_keepasstests_runtestcase104-regression.py",
	"winforms_dockpatterntests_runtestcase105-regression.py",
	"winforms_windowpatterntests_runtestcase106-regression.py"
]

uiaclientmoonlight_tests_list = [
	"moonlight_puzzlegametest_runtestcase301-regression.py",
	"moonlight_puzzlegametest_runtestcase302-regression.py",
	"moonlight_puzzlegametest_runtestcase303-regression.py",
	"moonlight_sl2withprismtest_runtestcase304-regression.py",
	"moonlight_sl2withprismtest_runtestcase305-regression.py",
	"moonlight_diggsearchtest_runtestcase306-regression.py",
	"moonlight_diggsearchtest_runtestcase307-regression.py",
	"moonlight_diggsearchtest_runtestcase308-regression.py",
	"moonlight_diggsearchtest_runtestcase309-regression.py"
]

uiaclientgtk_tests_list = [
	"gtk_fspot_runtestcase201-regression.py",
	"gtk_fspot_runtestcase202-regression.py",
	"gtk_fspot_runtestcase203-regression.py",
	"gtk_fspot_runtestcase204-regression.py",
	"gtk_fspot_runtestcase205-regression.py",
	"gtk_fspot_runtestcase206-regression.py",
	"gtk_fspot_runtestcase207-regression.py",
	"gtk_fspot_runtestcase208-regression.py"
]
