# the tests_list list keeps track of enabled tests.  A test will be
# executed only after the tests sample application is added to this list

# this allows tests to be worked on and developed in SVN, but only executed
# as part of the test suite when they are ready

# only add finished tests that should execute successfully to this list

tests_list = [
    "winforms/button_basic_ops.py",
    "winforms/checkbox_basic_ops.py",
    "winforms/checkedlistbox_basic_ops.py",
    "winforms/colordialog_basic_ops.py",
    "winforms/columnheader_basic_ops.py",
    "winforms/combobox_dropdown_ops.py",
    "winforms/combobox_dropdownlist_ops.py",
    "winforms/combobox_simple_ops.py",
    "winforms/combobox_stylechanges_basic_ops.py",
    "winforms/containercontrol_basic_ops.py",
    "winforms/contextmenu_basic_ops.py",
    "winforms/contextmenustrip_basic_ops.py",
    "winforms/datagrid_basic_ops.py",
    "winforms/datagridboolcolumn_basic_ops.py",
    "winforms/datagridtextboxcolumn_basic_ops.py",
    "winforms/datagridcomboboxcolumn_basic_ops.py",
    "winforms/datagridview_detail_ops.py",
    "winforms/datetimepicker_dropdown_ops.py",
    "winforms/datetimepicker_showupdown_ops.py",
    "winforms/domainupdown_basic_ops.py",
    "winforms/errorprovider_basic_ops.py",
    "winforms/flowlayoutpanel_basic_ops.py",
    "winforms/fontdialog_basic_ops.py",
    "winforms/form_basic_ops.py",
    "winforms/groupbox_basic_ops.py",
    "winforms/helpprovider_basic_ops.py",
    "winforms/hscrollbar_basic_ops.py",
    "winforms/label_basic_ops.py",
    "winforms/linklabel_basic_ops.py",
    "winforms/listbox_basic_ops.py", 
    "winforms/listview_detail_ops.py",
    "winforms/listview_largeimage_ops.py",
    "winforms/listview_smallimage_ops.py",
    "winforms/listview_list_ops.py",
    "winforms/maskedtextbox_basic_ops.py",
    "winforms/menustrip_basic_ops.py",
    "winforms/mainmenu_basic_ops.py",
    "winforms/monthcalendar_basic_ops.py",
    "winforms/notifyicon_basic_ops.py",
    "winforms/numericupdown_basic_ops.py",
    "winforms/openfiledialog_basic_ops.py",
    "winforms/pagesetupdialog_basic_ops.py",
    "winforms/panel_basic_ops.py",
    "winforms/picturebox_basic_ops.py",
    "winforms/printpreviewcontrol_basic_ops.py",
    "winforms/printpreviewdialog_basic_ops.py",
    "winforms/progressbar_basic_ops.py",
    "winforms/propertygrid_basic_ops.py",
    "winforms/radiobutton_basic_ops.py",
    "winforms/richtextbox_basic_ops.py",
    "winforms/savefiledialog_basic_ops.py",
    "winforms/scrollbar_basic_ops.py",
    "winforms/splitter_horizontal.py",
    "winforms/splitter_vertical.py",
    "winforms/statusbarpanel_basic_ops.py",
    "winforms/statusstrip_basic_ops.py",
    "winforms/tabcontrol_basic_ops.py",
    "winforms/tabpage_basic_ops.py",
    "winforms/tablelayoutpanel_basic_ops.py",
    "winforms/textbox_basic_ops.py",
    "winforms/threadexceptiondialog_basic_ops.py",
    "winforms/toolbar_basic_ops.py",
    "winforms/toolbarbutton_basic_ops.py",
    "winforms/toolstrip_basic_ops.py",
    "winforms/toolstripbutton_basic_ops.py",
    "winforms/toolstripcombobox_basic_ops.py",
    "winforms/toolstripdropdownbutton_basic_ops.py",
    "winforms/toolstriplabel_basic_ops.py",
    "winforms/toolstripmenuitem_basic_ops.py",
    "winforms/toolstripprogressbar_basic_ops.py",
    "winforms/toolstripseparator_basic_ops.py",
    "winforms/toolstripsplitbutton_basic_ops.py",
    "winforms/toolstriptextbox_basic_ops.py",
    "winforms/tooltip_basic_ops.py",
    "winforms/trackbar_basic_ops.py",
    "winforms/treeview_basic_ops.py",
    "winforms/vscrollbar_basic_ops.py",
]
