<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:template match="/">
  <html lang="en">
    <head>
      <title><xsl:value-of select="test/name"/></title>
      <link rel="stylesheet" type="text/css" href="procedures.css" media="all"/>
    </head>
    <body>
      <p class="header">
        <a href="http://www.mono-project.com/accessibility"><img src="uiaqa_logo.png" alt="UIAQA"/></a><br/><br/>
        <span id="testName"><xsl:value-of select="test/name"/></span><br/>
        <span id="documentName">Strongwind Test Script</span><br/>
        <span id="testDescription"><xsl:value-of select="test/description"/></span><br/>
      </p>

      <hr/>

      <h3>Test Procedures</h3>
      <table>
        <tr>
          <th id="stepNumber">Step</th>
          <th id="action">Action</th>
          <th id="expectedResult">Expected Results</th>
          <th id="screenshot">Screenshot</th>
          <th id="actualResult">Actual Results</th>
        </tr>
        <xsl:for-each select="test/procedures/step">
          <tr>
            <td><xsl:number/></td>
            <td><xsl:value-of select="action"/></td>
            <td><xsl:value-of select="expectedResult"/></td>
            <td>
              <a>
                <xsl:attribute name="href">
                  <xsl:value-of select="screenshot"/>
                </xsl:attribute>
                <img width="80" height="60">
                  <xsl:attribute name="src">
                    <xsl:value-of select="screenshot"/>
                  </xsl:attribute>
                </img>
              </a>
            </td>
            <td></td>
          </tr>
        </xsl:for-each>
      </table>

      <p id="signature">
        Tested By: ________________________________<br/>
        Date of Execution: ________________________________
      </p>
      <center>
        <a href="http://www.novell.com/linux"><img src="novell_logo.png" alt="Novell"/></a>
        <a href="http://www.medsphere.org/projects/strongwind/"><img src="strongwind_logo.png" alt="Strongwind"/></a>
        <p id="credits">Testing performed and report generated by <a href="http://www.medsphere.org/projects/strongwind/">Strongwind</a>
        </p>
      </center>
    </body>
  </html>
</xsl:template>
</xsl:stylesheet>
