thisdir = class/UIAutomationBridge
include ../../build/rules.make

LIBRARY = UIAutomationBridge.dll
LIBRARY_PACKAGE = accessibility

LIB_MCS_FLAGS = -r:System -r:WindowsBase -r:UIAutomationTypes

include ../../build/library.make
